# Generated by Django 5.0.2 on 2024-02-20 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(help_text='Enter the language of the book (e.g. English, Farsi, etc.)', max_length=100),
        ),
    ]
